"""Core data types for the mobile GUI agent."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass
class Observation:
    """Per-step observation from the mobile device."""

    screenshot_path: str
    note: str = ""


@dataclass
class GuiAction:
    """Action generated by the reasoning step."""

    action: str
    x: int | None = None
    y: int | None = None
    seconds: float | None = None
    status: str | None = None
    message: str = ""


@dataclass
class ReasoningOutcome:
    """Reasoning output including raw response and action transforms."""

    raw_response: str
    model_request: dict[str, Any] | None
    parsed_action: GuiAction
    adapted_action: GuiAction

