"""Core data types for the mobile GUI agent."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass
class Observation:
    """Per-step observation from the mobile device."""

    screenshot_path: str
    note: str = ""


@dataclass
class GuiAction:
    """Action generated by the reasoning step."""

    action: str
    x: int | None = None
    y: int | None = None
    x2: int | None = None
    y2: int | None = None
    seconds: float | None = None
    keycode: int | None = None
    status: str | None = None
    message: str = ""
    text: str = ""


@dataclass
class ReasoningOutcome:
    """Reasoning output including raw response and action transforms."""

    raw_response: str
    reasoning_content: str
    model_request: dict[str, Any] | None
    parsed_action: GuiAction
    adapted_action: GuiAction


@dataclass
class InferResult:
    """Inference output returned by GUI backend infer()."""

    raw_response: str
    model_request: dict[str, Any] | None
    reasoning_content: str = ""

